<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/Pytorch_Training_Pipeline_nnModule_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.drop(columns=['id', 'Unnamed: 32'], inplace=True)

# Define features (X) and target variable (y)
X = data.drop('diagnosis', axis=1)
y = data['diagnosis']

# Convert diagnosis to numerical values (0 for 'B', 1 for 'M')
y = y.map({'B': 0, 'M': 1})


# Split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Added random_state for reproducibility


# Scale the features using StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)


In [52]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [53]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [54]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

# convert array to tensor


In [55]:
import torch

In [56]:
x_train_tensor= torch.from_numpy(x_train)
x_test_tensor= torch.from_numpy(x_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [57]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [58]:
x_test_tensor.shape

torch.Size([114, 30])

# model selection

In [59]:
import torch.nn as nn
class myneuralnetwork(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out


In [60]:
# some important parameters

learning_rate = 0.1
epocs = 25


In [61]:
loss_function = nn.BCELoss()

# Training Pipeline

In [62]:
#create model
model = myneuralnetwork(x_train_tensor.shape[1])

x_train_tensor= x_train_tensor.type(torch.FloatTensor)
y_train_tensor= y_train_tensor.type(torch.FloatTensor)


# create optimizers
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)    # model.parameters is a function in pytorch that register all ur weight and bias , then iterate it

for epoch in range(epocs):

  # forward
  y_pred = model(x_train_tensor)
  # print(y_pred)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.reshape(-1,1))
  # print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # clear gradients
  optimizer.zero_grad()

  # backward
  loss.backward()
  # update
  optimizer.step()

  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.8050171136856079
Epoch: 2, Loss: 0.5946007370948792
Epoch: 3, Loss: 0.48581671714782715
Epoch: 4, Loss: 0.42094749212265015
Epoch: 5, Loss: 0.3773784935474396
Epoch: 6, Loss: 0.34569934010505676
Epoch: 7, Loss: 0.3213648200035095
Epoch: 8, Loss: 0.30191388726234436
Epoch: 9, Loss: 0.2858957052230835
Epoch: 10, Loss: 0.27239692211151123
Epoch: 11, Loss: 0.2608122229576111
Epoch: 12, Loss: 0.25072309374809265
Epoch: 13, Loss: 0.24183006584644318
Epoch: 14, Loss: 0.2339126467704773
Epoch: 15, Loss: 0.22680425643920898
Epoch: 16, Loss: 0.22037644684314728
Epoch: 17, Loss: 0.21452821791172028
Epoch: 18, Loss: 0.2091788351535797
Epoch: 19, Loss: 0.2042628526687622
Epoch: 20, Loss: 0.19972647726535797
Epoch: 21, Loss: 0.19552497565746307
Epoch: 22, Loss: 0.19162069261074066
Epoch: 23, Loss: 0.1879817098379135
Epoch: 24, Loss: 0.18458063900470734
Epoch: 25, Loss: 0.18139395117759705


In [63]:
model.linear.weight

Parameter containing:
tensor([[ 0.2364,  0.0940,  0.1722,  0.3916,  0.0208,  0.2246,  0.1316,  0.2232,
          0.0697, -0.0543,  0.3029,  0.0038,  0.0797,  0.0981, -0.0435, -0.0439,
          0.0333,  0.0227, -0.0318, -0.0074,  0.1250,  0.2423,  0.2301,  0.3877,
          0.0823,  0.1540,  0.1421,  0.3574,  0.0819,  0.0965]],
       requires_grad=True)

In [64]:
model.linear.bias

Parameter containing:
tensor([-0.3004], requires_grad=True)

# Evaluation

In [65]:
x_test_tensor= x_test_tensor.type(torch.FloatTensor)
y_test_tensor= y_test_tensor.type(torch.FloatTensor)

with torch.no_grad():
  y_pred = model(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  #accuracy
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")
  #print(y_pred)

Accuracy: 0.5689442753791809
