<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/Pytorch_Autograd_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install python-math

In [ ]:
def dy_dx(x):
  return 2*x
dy_dx(3)


6

In [ ]:
import math
def dy_dx(x):
  return 2*x*math.cos(2*x)
dy_dx(3)


5.761021719902196

# tensor derivatives

In [ ]:
import torch


In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x**4


In [ ]:
x , y

(tensor(2., requires_grad=True), tensor(16., grad_fn=<PowBackward0>))

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(32.)

In [49]:
x= torch.tensor(2.0, requires_grad=True)
y = x**2
z= torch.sin(y)




In [51]:
x, y, z

(tensor(2., requires_grad=True),
 tensor(4., grad_fn=<PowBackward0>),
 tensor(-0.7568, grad_fn=<SinBackward0>))

In [50]:
z.backward()

In [52]:
x.grad

tensor(-2.6146)

# neural network
### student placement

In [53]:
x = torch.tensor(2.0)
y= torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [60]:
def binary_loss_entropy(y_true, y_pred):
  epsilon = 1e-8
  y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
  return -(y_true*torch.log(y_pred) + (1-y_true)*torch.log(1-y_pred))

In [61]:
z = x*w + b
prediction = torch.sigmoid(z)

In [62]:
loss = binary_loss_entropy(y, prediction)

In [68]:
loss

tensor(2.1269)

In [65]:
# derivatives
#1
dz_dw = x
#2
dz_db = 1
#3
dypred_dz = prediction*(1-prediction)
#4
dloss_dy_pred = (prediction-y)/(prediction*(1-prediction))

In [66]:
dl_dw = dloss_dy_pred*dypred_dz*dz_dw
dl_db = dloss_dy_pred*dypred_dz*dz_db

In [67]:
print("gradient of loss w.r.t weight",{dl_dw})
print("gradient of loss w.r.t bias",{dl_db})

gradient of loss w.r.t weight {tensor(1.7616)}
gradient of loss w.r.t bias {tensor(0.8808)}


# Neural Network with Autograd

In [69]:
x = torch.tensor(2.0)
y= torch.tensor(0.0)

w= torch.tensor(1.0, requires_grad=True)
b= torch.tensor(0.0, requires_grad=True)

In [72]:
x , y , w , b

(tensor(2.),
 tensor(0.),
 tensor(1., requires_grad=True),
 tensor(0., requires_grad=True))

In [73]:
z = x*w +b
z

tensor(2., grad_fn=<AddBackward0>)

In [74]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.8808, grad_fn=<SigmoidBackward0>)

In [75]:
loss = binary_loss_entropy(y, y_pred)
loss

tensor(2.1269, grad_fn=<NegBackward0>)

In [76]:
loss.backward()

In [77]:
w.grad , b.grad

(tensor(1.7616), tensor(0.8808))

# Other important Features

In [80]:
x = torch.tensor([2.0, 5.0 , 7.0], requires_grad=True)
x

tensor([2., 5., 7.], requires_grad=True)

In [82]:
y = (x**2).sum()
y

tensor(78., grad_fn=<SumBackward0>)

In [83]:
y.backward()

In [84]:
x.grad

tensor([ 4., 10., 14.])

In [85]:
# Clear grad

x.grad.zero_()

tensor([0., 0., 0.])

# Disable Gradient Tracking
#### forward works but backward not

In [97]:
x = torch.tensor(2.0, requires_grad=True)

In [98]:
x

tensor(2., requires_grad=True)

In [99]:
#1- requires_grad=false
x.requires_grad=False


In [100]:
y = x** 2

In [101]:
y

tensor(4.)

In [102]:
#2- detach
z = x.detach()
z

tensor(2.)

In [103]:
y = x**2
y

tensor(4.)