<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/pytorch_basics_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch

In [34]:
if torch.cuda.is_available():
  print('GPU')
  print(torch.cuda.get_device_name(0))
else:
  print('CPU')

CPU


In [35]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [36]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
torch.empty(2,3)   # initialize any tensor

tensor([[-2.4807e-20,  3.1351e-41, -4.2282e-20],
        [ 3.1351e-41,  2.2826e+02,  2.2800e+02]])

In [38]:
torch.rand(2,3) #any random value

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

In [39]:
torch.manual_seed(10)# random value sa bachny ka liya
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [40]:
torch.tensor([[3,6,8,6],[6,9,8,4]])   # for our own choice

tensor([[3, 6, 8, 6],
        [6, 9, 8, 4]])

In [41]:
torch.arange(0,9,10)

tensor([0])

In [42]:
torch.linspace(0,1,10)   # range 0-10 evenly space

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [43]:
torch.eye(6) # tensor _______> like identity matrix

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [44]:
torch.full((3,3),4)  # tensor create of own choice and value

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

# Tensor Shapes

In [45]:
x = torch.tensor([[4,6,8],[9,8,7]])
x

tensor([[4, 6, 8],
        [9, 8, 7]])

In [46]:
x.shape

torch.Size([2, 3])

In [47]:
torch.empty_like(x)  # generate any tensor like x

tensor([[864985802068853760, 144968426413165569, 288525062565200897],
        [433202079557813761, 288527248754017793,    133387610685692]])

In [48]:
torch.zeros_like(x)# generate zeros tensor like x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [49]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Data Type

In [50]:
x.dtype

torch.int64

In [54]:
# assign dt to tensor

x= torch.tensor([[4,6,8],[9,8,7]], dtype= torch.int32)
x

tensor([[4, 6, 8],
        [9, 8, 7]], dtype=torch.int32)

In [55]:
y= torch.tensor([[9.0,6.8,7.0],[9.7,6.0,7.0]],dtype= torch.float64)
y

tensor([[9.0000, 6.8000, 7.0000],
        [9.7000, 6.0000, 7.0000]], dtype=torch.float64)

In [57]:
# convertion from one data type to other
x.to(torch.float64)


tensor([[4., 6., 8.],
        [9., 8., 7.]], dtype=torch.float64)

# maths operations

In [58]:
x+2

tensor([[ 6,  8, 10],
        [11, 10,  9]], dtype=torch.int32)

In [59]:
x-2

tensor([[2, 4, 6],
        [7, 6, 5]], dtype=torch.int32)

In [60]:
x*2

tensor([[ 8, 12, 16],
        [18, 16, 14]], dtype=torch.int32)

In [61]:
x^2

tensor([[ 6,  4, 10],
        [11, 10,  5]], dtype=torch.int32)

In [63]:
torch.round(y)

tensor([[ 9.,  7.,  7.],
        [10.,  6.,  7.]], dtype=torch.float64)

In [66]:
x1 = torch.tensor([[1.8,2.2,3],[4.8,5.0,6.0]])

In [68]:
torch.ceil(x1)

tensor([[2., 3., 3.],
        [5., 5., 6.]])

In [69]:
torch.floor(x1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [70]:
torch.clamp(x1,min=2,max=5)

tensor([[2.0000, 2.2000, 3.0000],
        [4.8000, 5.0000, 5.0000]])