<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/Pytorch_Training_Pipeline_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.drop(columns=['id', 'Unnamed: 32'], inplace=True)

# Define features (X) and target variable (y)
X = data.drop('diagnosis', axis=1)
y = data['diagnosis']

# Convert diagnosis to numerical values (0 for 'B', 1 for 'M')
y = y.map({'B': 0, 'M': 1})


# Split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Added random_state for reproducibility


# Scale the features using StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)


In [131]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [132]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [133]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

# convert array to tensor


In [134]:
import torch

In [135]:
x_train_tensor= torch.from_numpy(x_train)
x_test_tensor= torch.from_numpy(x_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [136]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [137]:
x_test_tensor.shape

torch.Size([114, 30])

# model selection

In [138]:
class myneuralnetwork():

  def __init__(self, x):

    self.weights = torch.rand(x.shape[1], 1 , requires_grad=True, dtype=torch.float64)
    self.bias = torch.zeros(1, requires_grad=True, dtype=torch.float64)


  def forward(self, x):
    z = torch.matmul(x,self.weights)+ self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss(self, y_pred, y):
    epilson = 1e-7
    y_pred = torch.clamp(y_pred, epilson, 1 - epilson)
    loss = -y * torch.log(y_pred) - (1 - y) * torch.log(1 - y_pred)
    return loss.mean()

In [139]:
# some important parameters

learning_rate = 0.1
epocs = 20


# Training Pipeline

In [140]:
model = myneuralnetwork(x_train_tensor)

for epoch in range(epocs):
# forward
  y_pred = model.forward(x_train_tensor)
  #print(y_pred)
# loss cal
  loss = model.loss(y_pred, y_train_tensor)
  #print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

 # backward
  loss.backward()
# update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
#  zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.258091362493643
Epoch: 2, Loss: 3.1194101705575097
Epoch: 3, Loss: 2.9736752676699107
Epoch: 4, Loss: 2.821516735558547
Epoch: 5, Loss: 2.6627958141069104
Epoch: 6, Loss: 2.49578591394311
Epoch: 7, Loss: 2.3239145334726445
Epoch: 8, Loss: 2.1539348734701735
Epoch: 9, Loss: 1.9896920962947966
Epoch: 10, Loss: 1.8307533001797673
Epoch: 11, Loss: 1.6777199912021066
Epoch: 12, Loss: 1.5352567508080732
Epoch: 13, Loss: 1.403933333562181
Epoch: 14, Loss: 1.2824421575852245
Epoch: 15, Loss: 1.174192777697455
Epoch: 16, Loss: 1.0799518561446686
Epoch: 17, Loss: 1.0031183671423367
Epoch: 18, Loss: 0.9425055277752974
Epoch: 19, Loss: 0.896072226469531
Epoch: 20, Loss: 0.8612292224593381


In [141]:
model.weights

tensor([[-0.0689],
        [-0.1223],
        [-0.1106],
        [ 0.2462],
        [ 0.2215],
        [-0.5014],
        [-0.4592],
        [ 0.0967],
        [ 0.0811],
        [ 0.1991],
        [ 0.2755],
        [ 0.0919],
        [-0.1908],
        [ 0.5354],
        [ 0.3292],
        [ 0.2494],
        [ 0.0321],
        [ 0.3463],
        [ 0.1616],
        [ 0.1028],
        [ 0.1792],
        [ 0.4200],
        [ 0.2564],
        [ 0.1599],
        [ 0.3763],
        [ 0.2490],
        [-0.2403],
        [-0.4473],
        [-0.1651],
        [-0.2512]], dtype=torch.float64, requires_grad=True)

In [142]:
model.bias

tensor([-0.1072], dtype=torch.float64, requires_grad=True)

# Evaluation

In [143]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  #accuracy
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")
  #print(y_pred)

Accuracy: 0.5
