<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/Pytorch_nnModule_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
import torch.nn as nn

In [31]:
class Model(nn.Module):
    def __init__(self, new_features):
        super(Model, self).__init__()  # Initialize the parent class
        self.linear = nn.Linear(new_features, 1)
        self.sigmoid = nn.Sigmoid()  # Use Sigmoid instead of sigmoid

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [32]:

# Dataset creation
x = torch.rand(4, 3)

# Model creation
model = Model(x.shape[1])

# Forward calculation and printing the output
output = model(x)
print(output)

tensor([[0.4653],
        [0.4947],
        [0.4539],
        [0.4665]], grad_fn=<SigmoidBackward0>)


In [33]:
model.linear.weight

Parameter containing:
tensor([[-0.2055, -0.5266,  0.0604]], requires_grad=True)

In [34]:
model.linear.bias

Parameter containing:
tensor([0.2029], requires_grad=True)

In [36]:
!pip install torchinfo
from torchinfo import summary

summary(model, input_size=(4,3))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [4, 1]                    --
├─Linear: 1-1                            [4, 1]                    4
├─Sigmoid: 1-2                           [4, 1]                    --
Total params: 4
Trainable params: 4
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Create NN


In [37]:
class Model(nn.Module):
    def __init__(self, new_features):
        super(Model, self).__init__()
        self.linear1 = nn.Linear(new_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [39]:
x = torch.rand(10, 5)

# Model creation
model = Model(x.shape[1])

# Forward calculation and printing the output
output = model(x)
print(output)

tensor([[0.5600],
        [0.5716],
        [0.5875],
        [0.5711],
        [0.5623],
        [0.5438],
        [0.6041],
        [0.5529],
        [0.5351],
        [0.5789]], grad_fn=<SigmoidBackward0>)


In [42]:
model.linear1.weight , model.linear2.weight

(Parameter containing:
 tensor([[-0.3229, -0.1279,  0.4251, -0.0959,  0.2831],
         [ 0.3881,  0.0301,  0.3441,  0.1398,  0.3204],
         [-0.0884, -0.0641,  0.2297, -0.0571,  0.3131]], requires_grad=True),
 Parameter containing:
 tensor([[ 0.4707, -0.4773,  0.4716]], requires_grad=True))

In [43]:
model.linear2.bias , model.linear1.bias

(Parameter containing:
 tensor([0.2117], requires_grad=True),
 Parameter containing:
 tensor([0.3931, 0.0348, 0.1617], requires_grad=True))

In [44]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential container

In [45]:
class Model(nn.Module):
    def __init__(self, new_features):
        super(Model, self).__init__()
        self.network = nn.Sequential(

            nn.Linear(new_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()  )

    def forward(self, x):
        out = self.network(x)
        return out

In [46]:
x = torch.rand(10, 5)

# Model creation
model = Model(x.shape[1])

# Forward calculation and printing the output
output = model(x)
print(output)

tensor([[0.4212],
        [0.4452],
        [0.4225],
        [0.4518],
        [0.4411],
        [0.4324],
        [0.4480],
        [0.4429],
        [0.4286],
        [0.4223]], grad_fn=<SigmoidBackward0>)


In [47]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00