<a href="https://colab.research.google.com/github/Bisma-Shafiq/Deep-Learning_Pytorch/blob/main/pytorch_basics_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
if torch.cuda.is_available():
  print('GPU')
  print(torch.cuda.get_device_name(0))
else:
  print('CPU')

CPU


In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.empty(2,3)   # initialize any tensor

tensor([[-5.8303e+01,  3.2029e-41, -9.9730e+06],
        [ 4.5555e-41,  8.9683e-44,  0.0000e+00]])

In [7]:
torch.rand(2,3) #any random value

tensor([[0.4113, 0.8259, 0.7654],
        [0.9434, 0.8023, 0.0656]])

In [8]:
torch.manual_seed(10)# random value sa bachny ka liya
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [9]:
torch.tensor([[3,6,8,6],[6,9,8,4]])   # for our own choice

tensor([[3, 6, 8, 6],
        [6, 9, 8, 4]])

In [10]:
torch.arange(0,9,10)

tensor([0])

In [11]:
torch.linspace(0,1,10)   # range 0-10 evenly space

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [12]:
torch.eye(6) # tensor _______> like identity matrix

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [13]:
torch.full((3,3),4)  # tensor create of own choice and value

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

# Tensor Shapes

In [14]:
x = torch.tensor([[4,6,8],[9,8,7]])
x

tensor([[4, 6, 8],
        [9, 8, 7]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)  # generate any tensor like x

tensor([[    139628499185072,     139628499185072,                   0],
        [                  0,                   0, 7310593858020254331]])

In [17]:
torch.zeros_like(x)# generate zeros tensor like x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Data Type

In [19]:
x.dtype

torch.int64

In [20]:
# assign dt to tensor

x= torch.tensor([[4,6,8],[9,8,7]], dtype= torch.int32)
x

tensor([[4, 6, 8],
        [9, 8, 7]], dtype=torch.int32)

In [21]:
y= torch.tensor([[9.0,6.8,7.0],[9.7,6.0,7.0]],dtype= torch.float64)
y

tensor([[9.0000, 6.8000, 7.0000],
        [9.7000, 6.0000, 7.0000]], dtype=torch.float64)

In [22]:
# convertion from one data type to other
x.to(torch.float64)


tensor([[4., 6., 8.],
        [9., 8., 7.]], dtype=torch.float64)

# maths operations

In [23]:
x+2

tensor([[ 6,  8, 10],
        [11, 10,  9]], dtype=torch.int32)

In [24]:
x-2

tensor([[2, 4, 6],
        [7, 6, 5]], dtype=torch.int32)

In [25]:
x*2

tensor([[ 8, 12, 16],
        [18, 16, 14]], dtype=torch.int32)

In [26]:
x^2

tensor([[ 6,  4, 10],
        [11, 10,  5]], dtype=torch.int32)

In [27]:
torch.round(y)

tensor([[ 9.,  7.,  7.],
        [10.,  6.,  7.]], dtype=torch.float64)

In [28]:
x1 = torch.tensor([[1.8,2.2,3],[4.8,5.0,6.0]])

In [29]:
torch.ceil(x1)

tensor([[2., 3., 3.],
        [5., 5., 6.]])

In [30]:
torch.floor(x1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
torch.clamp(x1,min=2,max=5)

tensor([[2.0000, 2.2000, 3.0000],
        [4.8000, 5.0000, 5.0000]])

# Reduction Operation

In [37]:
a = torch.randint(size=(3,4),low=0, high = 10, dtype=torch.float32)
a

tensor([[6., 2., 8., 9.],
        [2., 0., 9., 9.],
        [4., 4., 9., 4.]])

In [38]:
# sum of tensor
torch.sum(a)

tensor(66.)

In [39]:
# sum alog columns
torch.sum(a, dim=0)

tensor([12.,  6., 26., 22.])

In [40]:
# sum along rows
torch.sum(a, dim=1)

tensor([25., 20., 21.])

In [41]:
# mean
torch.mean(a)


tensor(5.5000)

In [42]:
torch.mean(a,dim=0)

tensor([4.0000, 2.0000, 8.6667, 7.3333])

In [43]:
torch.mean(a,dim=1)

tensor([6.2500, 5.0000, 5.2500])

In [44]:
# median
torch.median(a)

tensor(4.)

In [45]:
torch.median(a,dim=0)

torch.return_types.median(
values=tensor([4., 2., 9., 9.]),
indices=tensor([2, 0, 1, 0]))

In [46]:
torch.median(a,dim=1)

torch.return_types.median(
values=tensor([6., 2., 4.]),
indices=tensor([0, 0, 1]))

In [47]:
# product
torch.prod(a)

tensor(0.)

In [48]:
#standard deviation
torch.std(a)

tensor(3.2613)

In [49]:
# variance
torch.var(a)

tensor(10.6364)

In [50]:
# argmax
torch.argmax(a)

tensor(3)

# Matrix Multiplication

In [51]:
b = torch.randint(size=(3,4),low=0, high = 10, dtype=torch.float32)
c= torch.randint(size=(4,3),low=0, high = 10, dtype=torch.float32)

In [52]:
b , c

(tensor([[4., 5., 4., 0.],
         [8., 9., 3., 0.],
         [9., 3., 7., 9.]]),
 tensor([[5., 2., 9.],
         [6., 6., 2.],
         [8., 9., 6.],
         [9., 1., 9.]]))

In [53]:
# matrix multiplication
torch.matmul(b,c)

tensor([[ 82.,  74.,  70.],
        [118.,  97., 108.],
        [200., 108., 210.]])

In [56]:
# dot product
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])
torch.dot(vector1,vector2)

tensor(32)

In [61]:
# transponse
b
torch.transpose(b,0,1)

tensor([[4., 8., 9.],
        [5., 9., 3.],
        [4., 3., 7.],
        [0., 0., 9.]])

In [66]:
t = torch.randint(size = (3,3),low = 0, high = 10, dtype=torch.float32)
t

tensor([[2., 1., 2.],
        [9., 7., 2.],
        [9., 4., 4.]])

In [68]:
# inverse
torch.inverse(t)

tensor([[-0.6250, -0.1250,  0.3750],
        [ 0.5625,  0.3125, -0.4375],
        [ 0.8438, -0.0313, -0.1562]])

In [69]:
#determinent
torch.det(t)

tensor(-32.)

# Inplace Operation

In [71]:
a = torch.rand(2,3)
b= torch.rand(2,3)

In [73]:
a, b


(tensor([[0.8879, 0.9792, 0.2627],
         [0.1800, 0.6750, 0.1424]]),
 tensor([[0.3790, 0.0055, 0.6368],
         [0.3295, 0.2203, 0.1821]]))

In [74]:
a+b

tensor([[1.2669, 0.9847, 0.8995],
        [0.5095, 0.8953, 0.3245]])

In [75]:
a.add_(b)

tensor([[1.2669, 0.9847, 0.8995],
        [0.5095, 0.8953, 0.3245]])

In [76]:
b.add_(a)

tensor([[1.6459, 0.9901, 1.5363],
        [0.8390, 1.1155, 0.5065]])

In [77]:
a

tensor([[1.2669, 0.9847, 0.8995],
        [0.5095, 0.8953, 0.3245]])

In [78]:
b

tensor([[1.6459, 0.9901, 1.5363],
        [0.8390, 1.1155, 0.5065]])

# Copy Tensor

In [79]:
a= torch.rand(2,3)
a

tensor([[0.3241, 0.7375, 0.5283],
        [0.9306, 0.3213, 0.3537]])

In [80]:
b=a
b

tensor([[0.3241, 0.7375, 0.5283],
        [0.9306, 0.3213, 0.3537]])

In [82]:
# if i change in a b also chnge
a[0][0]=0
a , b

(tensor([[0.0000, 0.7375, 0.5283],
         [0.9306, 0.3213, 0.3537]]),
 tensor([[0.0000, 0.7375, 0.5283],
         [0.9306, 0.3213, 0.3537]]))

In [84]:
# copy tensor

b=a.clone()
b

tensor([[0.0000, 0.7375, 0.5283],
        [0.9306, 0.3213, 0.3537]])

In [86]:
a[0][0]=1
a , b

(tensor([[1.0000, 0.7375, 0.5283],
         [0.9306, 0.3213, 0.3537]]),
 tensor([[0.0000, 0.7375, 0.5283],
         [0.9306, 0.3213, 0.3537]]))

# Reshaping Tensor

In [93]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [96]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [97]:
a.flatten()  # convert to 1dim

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
# returns a view of a given tensor with its dimensions permuted or rearranged according to a specific order
b = torch.rand([2,3,4])
b

tensor([[[0.3325, 0.2877, 0.6533, 0.3310],
         [0.6552, 0.2441, 0.1906, 0.4875],
         [0.7936, 0.9259, 0.6105, 0.2030]],

        [[0.7614, 0.6949, 0.7133, 0.3333],
         [0.4325, 0.7307, 0.7065, 0.8321],
         [0.2001, 0.8140, 0.3055, 0.4874]]])

In [100]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])